module.exports = {
    "words": [  
        "daisy",
        "mouse",
        "swan",
        "alpaca",
        "black widow",
        "anteater",
        "bunny",
        "beaver",
        "porcupine",
        "flamingo",
        "ostrich",
        "grizzly",
        "ape",
        "deer",
        "stork",
        "chameleon",
        "poodle",
        "python",
        "iguana",
        "hamster",
        "pelican",
        "omnivore",
        "dove",
        "flounder",
        "spider",
        "elephant",
        "hedgehog",
        "boar",
        "doe",
        "chicken",
        "pony",
        "crab",
        "tortoise",
        "octopus",
        "jackal",
        "goose",
        "robin",
        "rooster",
        "seahorse",
        "ant",
        "cockroach",
        "snail",
        "snake",
        "toad",
        "dolphin",
        "turkey",
        "badger",
        "piranha",
        "panda",
        "toucan",
        "housecat",
        "black bear",
        "mule",
        "hare",
        "parakeet",
        "cricket",
        "sloth",
        "clownfish",
        "eagle",
        "gerbil",
        "bird",
        "cow",
        "caribou",
        "ox",
        "humpback whale",
        "buffalo",
        "falcon",
        "seal",
        "frog",
        "albatross",
        "gorilla",
        "koala",
        "kitten",
        "partridge",
        "bass",
        "crocodile",
        "reindeer",
        "cub",
        "worm",
        "dog",
        "bulldog",
        "earthworm",
        "snapping turtle",
        "stallion",
        "emu",
        "guppy",
        "elk",
        "herbivore",
        "hen",
        "wooly mammoth",
        "carnivore",
        "hippopotamus",
        "mole",
        "duckling",
        "dingo",
        "bear",
        "tapir",
        "ferret",
        "alligator",
        "blue whale",
        "sea lion",
        "dragonfly",
        "oyster",
        "goat",
        "fly",
        "armadillo",
        "walrus",
        "calf",
        "wolf",
        "vampire bat",
        "clam",
        "bluebird",
        "warthog",
        "horse",
        "lemur",
        "yak",
        "salmon",
        "salamander",
        "lemming",
        "manatee",
        "polar bear",
        "butterfly",
        "tree frog",
        "zebra",
        "bat",
        "canary",
        "cougar",
        "gopher",
        "camel",
        "cheetah",
        "chick",
        "hummingbird",
        "macaw",
        "dinosaur",
        "coyote",
        "hyena",
        "anemone",
        "beagle",
        "squid",
        "barracuda",
        "penguin",
        "catfish",
        "rhinoceros",
        "squirrel",
        "gazelle",
        "antelope",
        "owl",
        "kangaroo",
        "raccoon",
        "whale",
        "tuna",
        "chipmunk",
        "hermit crab",
        "eagle",
        "wildebeest",
        "jellyfish",
        "fox",
        "hornet",
        "pike",
        "duck",
        "sheep",
        "pig",
        "rat",
        "stingray",
        "dragon",
        "starfish",
        "joey",
        "cobra",
        "eel",
        "hawk",
        "panther",
        "giraffe",
        "meerkat",
        "dodo bird",
        "pigeon",
        "vulture",
        "cat",
        "grasshopper",
        "rabbit",
        "parrot",
        "monkey",
        "bumblebee",
        "swordfish",
        "shrew",
        "unicorn",
        "platypus",
        "seagull",
        "raven",
        "crow",
        "moose",
        "lobster",
        "leopard",
        "turtle",
        "weasel",
        "shrimp",
        "puppy",
        "baboon",
        "tiger",
        "jaguar",
        "mosquito",
        "lion",
        "shark",
        "possum",
        "llama",
        "groundhog",
        "crane",
        "anaconda",
        "donkey",
        "chimpanzee",
        "moth",
        "ram",
        "tadpole",
        "ladybug",
        "otter",
        "narwhal",
        "red panda",
        "skunk",
        "sea cucumber",
        "tarantula",
        "bison",
        "wasp",
        "lamb",
        "caterpillar",
        "sabertooth tiger",
        "sea turtle",
        "food processor",
        "raisin",
        "shortening",
        "sandwich",
        "flatbread",
        "ribs",
        "celery",
        "chocolate",
        "mayonnaise",
        "punch",
        "slice",
        "deep-dish pizza",
        "grinder",
        "cheeseburger",
        "kebab",
        "hot fudge sundae",
        "drain",
        "olive oil",
        "fruitcake",
        "salad",
        "tea",
        "date",
        "lobster",
        "white bread",
        "kidney beans",
        "noodle",
        "yolk",
        "cabbage",
        "quinoa",
        "American cheese",
        "peanut",
        "deep fryer",
        "sour cream",
        "dice",
        "pickle",
        "spatula",
        "hamburger",
        "spaghetti",
        "meatloaf",
        "olive",
        "fork",
        "pepperoni pizza",
        "rolling pin",
        "soybean",
        "knife",
        "french fries",
        "microwave",
        "milkshake",
        "sponge cake",
        "hot dog",
        "pepperoni",
        "toast",
        "ham",
        "kettle",
        "apple",
        "onion",
        "turnip",
        "sesame seeds",
        "honey",
        "pie",
        "mashed potatoes",
        "cornflakes",
        "sunflower seeds",
        "carrot cake",
        "crackers",
        "pumpkin pie",
        "turkey",
        "broccoli",
        "cookie sheet",
        "peel",
        "apple sauce",
        "cookies and cream",
        "pita",
        "toaster oven",
        "cantaloupe",
        "frosting",
        "horseradish",
        "taste",
        "soda",
        "fortune cookie",
        "salad dressing",
        "cinnamon",
        "mushroom",
        "taco",
        "pizza",
        "whisk",
        "BLT",
        "ratatouille",
        "kiwi",
        "apple pie",
        "Cheerios",
        "mason jar",
        "croutons",
        "butterscotch",
        "ginger",
        "ice cream",
        "teaspoon",
        "teriyaki",
        "ice cube",
        "grilled cheese",
        "Caesar salad",
        "scone",
        "strawberry",
        "dough",
        "eggnog",
        "sloppy joe",
        "string cheese",
        "fried rice",
        "knife set",
        "salsa",
        "cinnamon roll",
        "cranberry",
        "peanut butter",
        "chocolate milk",
        "milk",
        "zucchini",
        "carrot",
        "chicken tenders",
        "sparkling water",
        "mozzarella cheese",
        "popcorn",
        "tomato",
        "grapefruit",
        "restaurant",
        "lunchmeat",
        "preheat",
        "fish and chips",
        "cookie",
        "sushi",
        "rice pudding",
        "swallow",
        "food pyramid",
        "cupcake",
        "burn",
        "pudding",
        "gyro",
        "dessert",
        "chives",
        "radish",
        "hazelnut",
        "apple juice",
        "yeast",
        "provisions",
        "simmer",
        "raw",
        "waffle",
        "arugula",
        "sugar cookie",
        "whipped cream",
        "puree",
        "potato skins",
        "refrigerate",
        "deviled eggs",
        "salt shaker",
        "cherry",
        "fruit salad",
        "mustard",
        "eclair",
        "cake mix",
        "garlic",
        "colander",
        "unleavened",
        "sweet tooth",
        "fruit smoothie",
        "cake",
        "Pop Tart",
        "mousse",
        "ketchup",
        "muffin",
        "cooking oil",
        "herbs",
        "lettuce",
        "potato",
        "fajita",
        "angel hair pasta",
        "tempura",
        "tortilla chips",
        "garbanzo bean",
        "burrito",
        "mozzarella sticks",
        "soak",
        "lentil",
        "curry",
        "chili pepper",
        "pizza stone",
        "pear",
        "parboil",
        "to boil",
        "saute",
        "cheesecake",
        "meat",
        "cherry pie",
        "microwave dinner",
        "stir-fry",
        "digest",
        "tablespoon",
        "mash",
        "lasagna",
        "jam",
        "caramelize",
        "guacamole",
        "salami",
        "linguine",
        "octopus",
        "rice",
        "tenderize",
        "alphabet soup",
        "cookbook",
        "mixing bowl",
        "order",
        "scramble",
        "spam",
        "measuring spoon",
        "caviar",
        "chickpea",
        "chicken noodle soup",
        "egg timer",
        "skim milk",
        "coffee",
        "prime rib",
        "potato chips",
        "pita pocket",
        "blueberry",
        "almonds",
        "ranch dressing",
        "chopsticks",
        "napkin",
        "sun-dried tomatoes",
        "tuna",
        "summer squash",
        "bok choy",
        "salmon",
        "cornmeal",
        "corn on the cob",
        "to poach",
        "to blanch",
        "nachos",
        "souffle",
        "cereal",
        "anchovies",
        "tomato soup",
        "fried chicken",
        "chef",
        "patty",
        "coffee pot",
        "pizza cutter",
        "peanut butter cookies",
        "jelly",
        "slow cooker",
        "to melt",
        "waffle iron",
        "pork",
        "macaroni and cheese",
        "buffalo wings",
        "thin crust pizza",
        "corn",
        "gravy",
        "frozen yogurt",
        "skewer",
        "fillet",
        "enchilada",
        "poultry",
        "vanilla extract",
        "pot stickers",
        "wok",
        "clam chowder",
        "churro",
        "drink",
        "nutritious",
        "French onion dip",
        "orange chicken",
        "fondue",
        "lamb",
        "edamame",
        "chow mein",
        "pineapple",
        "jambalaya",
        "refried beans",
        "jar opener",
        "glaze",
        "pumpkin",
        "sifter",
        "crab",
        "spinach",
        "meringue",
        "yogurt",
        "whip",
        "lemon",
        "strudel",
        "coconut cream pie",
        "coaster",
        "saltine crackers",
        "griddle",
        "hot sauce",
        "dinner roll",
        "clam",
        "flour",
        "funnel",
        "silverware",
        "pretzel",
        "Tupperware",
        "corn flakes",
        "chicken nuggets",
        "sherbet",
        "chicken",
        "creme brulee",
        "fry",
        "jalapeno",
        "saffron",
        "pastry",
        "green bean",
        "scoop",
        "brisket",
        "soft boil",
        "chips and salsa",
        "squid",
        "ramekin",
        "take-out",
        "scrambled eggs",
        "overcook",
        "chicken salad sandwich",
        "jell-o",
        "asparagus",
        "chicken fried steak",
        "stove",
        "cream",
        "popsicle",
        "wheat bread",
        "vanilla pudding",
        "gingerbread man",
        "whole milk",
        "capers",
        "provolone cheese",
        "nutmeg",
        "cheese",
        "juicer machine",
        "ice cream cone",
        "chicken pot pie",
        "tarragon",
        "mouth",
        "kumquat",
        "chocolate cake",
        "pecan",
        "snickerdoodle",
        "plum",
        "corndog",
        "ladle",
        "egg rolls",
        "bread bowl",
        "chocolate chip cookie",
        "tamale",
        "almond milk",
        "candy",
        "drive-through",
        "rice cooker",
        "hummus",
        "raspberry",
        "wasabi",
        "long grain",
        "steak knife",
        "rye",
        "chocolate chip",
        "Swiss cheese",
        "cooling rack",
        "cloves",
        "soft pretzel",
        "produce",
        "to broil",
        "egg",
        "fritter",
        "Bruscetta",
        "grape",
        "omelet",
        "ginger ale",
        "carne asada",
        "chickpeas",
        "ice cream sandwich",
        "tangerine",
        "marshmallow",
        "pancake",
        "green onion",
        "sweeten",
        "cuisine",
        "cheese grater",
        "maple syrup",
        "Bundt cake",
        "dinner",
        "tortilla",
        "yam",
        "tapioca pudding",
        "pulp",
        "angel food cake",
        "stomach",
        "graham cracker",
        "croissant",
        "coffee maker",
        "grill",
        "soy milk",
        "vegetable peeler",
        "donut",
        "sweet",
        "halibut",
        "garlic press",
        "chow",
        "junk food",
        "oatmeal raisin cookie",
        "sauce pan",
        "orange",
        "deep-fry",
        "salt",
        "marinade",
        "feta cheese",
        "bread",
        "pinto beans",
        "lard",
        "pork chop",
        "oven",
        "marinate",
        "sea salt",
        "sugar",
        "French toast",
        "hash browns",
        "spork",
        "broil",
        "roast",
        "Dutch oven",
        "cornbread",
        "wedding cake",
        "thicken",
        "dairy",
        "jellybeans",
        "cake pan",
        "gingerbread house",
        "eggplant",
        "squash",
        "veggie burger",
        "Canadian bacon",
        "animal crackers",
        "toaster",
        "broth",
        "brownie",
        "tongs",
        "walnut",
        "meatball",
        "low-fat",
        "citrus",
        "liver",
        "stew",
        "coconut",
        "brown rice",
        "Twinkies",
        "watermelon",
        "muffin tin",
        "hungry",
        "refreshments",
        "granola bar",
        "lima bean",
        "tater tots",
        "turkey bacon",
        "wooden spoon",
        "cucumber",
        "toss",
        "oatmeal",
        "cashew",
        "pea",
        "shrimp",
        "pressure cooker",
        "freeze",
        "pasta",
        "ice cream scoop",
        "garnish",
        "sardines",
        "crunch",
        "key lime pie",
        "apple cider",
        "Girl Scout cookies",
        "fudge",
        "peach",
        "parmesan cheese"
    ]
}